version: '2'
services:

  go: &go
    image: golang:1.7
    working_dir: /go/src/github.com/gnhuy91/stringsvc
    volumes:
      - .:/go/src/github.com/gnhuy91/stringsvc

  go-test:
    <<: *go
    command: go test -v

  go-bench:
    <<: *go
    command: go test -run=xxx -bench=.

  go-build:
    <<: *go
    command: sh -c 'cd cmd/stringsvc && rm -f bin/stringsvc && go build -o bin/stringsvc && chmod 777 bin/stringsvc'
    environment:
      CGO_ENABLED: 0
